/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    Input: typeof import('./src/components/Input.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    MySubTitle: typeof import('./src/components/MySubTitle.vue')['default']
    MyTitle: typeof import('./src/components/MyTitle.vue')['default']
    MyTransition: typeof import('./src/components/MyTransition.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    Provider: typeof import('./src/components/Provider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpcaseInput: typeof import('./src/components/UpcaseInput.vue')['default']
  }
}
